dist: xenial

language: node_js

node_js:
  - "8"

env:
  global:
    - IMAGE_NAME=plus3it/tests-harness

stages:
  - lint
  - test
  - deploy

services:
  - docker

jobs:
  include:
    - stage: lint
      name: EditorConfig Syntax Verification
      install:
        - npm install -g eclint
        - eclint --version
      script: eclint check
    - stage: lint
      name: Shell Script Syntax Verification
      script: make sh/lint
    - stage: lint
      name: JSON Lint/Format Verification
      script: make json/lint
    - stage: lint
      name: Terraform Lint/Format Verification
      install:
        - make terraform/install
        - make terraform-docs/install
      script:
        - make terraform/lint
        - make docs/lint
    - stage: test
      name: Makefile unit tests
      script:
        - bash bin/conditional-makefile-unit-tests.sh
    - stage: deploy
      if: branch = master AND type = push AND repo = plus3it/tardigrade-ci
      before_script:
        - |
          PRIOR_VERSION=$(git describe --abbrev=0 --tags)
          RELEASE_VERSION=$(grep current_version $TRAVIS_BUILD_DIR/.bumpversion.cfg | sed 's/^.*= //' )
          RELEASE_BODY="* [tardigrade-ci v$RELEASE_VERSION CHANGELOG](https://github.com/plus3it/tardigrade-ci/blob/$RELEASE_VERSION/CHANGELOG.md)"
          export PRIOR_VERSION RELEASE_VERSION RELEASE_BODY
      script: skip
      before_deploy:
        - |
          (set -x; git tag -a $RELEASE_VERSION -m $RELEASE_VERSION)
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
          docker tag "$IMAGE_NAME" "${IMAGE_NAME}:$RELEASE_VERSION"
      deploy:
        provider: releases
        api_key:
          secure:
        name: $RELEASE_VERSION
        body: $RELEASE_BODY
        script: docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${version}"
        tag_name: $RELEASE_VERSION
        target_commitish: $TRAVIS_COMMIT
        draft: false
        on:
          branch: master
          repo: plus3it/tardigrade-ci
          condition: '"$PRIOR_VERSION" != "$RELEASE_VERSION"'
